# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publicatin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
