# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20160723_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
    ]
