# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='descrp',
        ),
    ]
